CREATE TABLE EMPLOYEE
(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SALARY INTEGER NOT NULL,
    DEPT VARCHAR(255) NOT NULL
);

INSERT INTO EMPLOYEE (ID,NAME,SALARY,DEPT)
VALUES (1000,'Nimit',5000,'Java');
INSERT INTO EMPLOYEE (ID,NAME,SALARY,DEPT)
VALUES (1001,'Shailesh',5000,'Java');

